apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: alertmanager
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: alertmanager.k8s.goshare2.com
    http:
      paths:
      - path: /
        backend:
          serviceName: alertmanager-main 
          servicePort: 9093
