apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: prometheus-k8s
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: prometheus.k8s.goshare2.com
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus-k8s 
          servicePort: 9090
